version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7002:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    restart: always